name: monitor_bloc
description: BLoC for GSMLG Monitor feature
publish_to: none
resolution: workspace

version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  app_database: any
  bloc: any
  crypto: any
  equatable: any
  flutter:
    sdk: flutter
  meta: any
  monitor_models: any
  multicast_dns: any
  web_socket_channel: any
