name: app_components
description: Reusable UI components for the app.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_blue_plus: ^2.2.1

  bluetooth_bloc: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
