name: monitor_agent
description: System metrics agent daemon for GSMLG Monitor
publish_to: none
resolution: workspace

version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  args: any
  monitor_models: any
  multicast_dns: any
  pointycastle: any
  shelf: any
  shelf_web_socket: any
  web_socket_channel: any
