name: app_system_metrics
description: Retrieve CPU, GPU, NPU, and memory metrics
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  app_system_metrics_platform_interface: any
  app_system_metrics_android: any
  app_system_metrics_ios: any
  app_system_metrics_linux: any
  app_system_metrics_macos: any
  app_system_metrics_windows: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.4
  build_runner: ^2.4.9
