import 'package:equatable/equatable.dart';

/// Where chat inference should run.
enum ChatInferenceMode {
  /// Use an on-device model through flutter_gemma.
  local,

  /// Use a remote LLM API.
  remote,
}

/// Supported remote LLM API families.
enum RemoteLlmProvider {
  /// APIs that expose an OpenAI-compatible `/chat/completions` endpoint.
  openAiCompatible,
}

/// App-owned generation stream event.
///
/// Repositories adapt provider-specific streaming formats into this type so the
/// BLoC does not depend on a specific model SDK or HTTP API.
sealed class ChatGenerationChunk extends Equatable {
  const ChatGenerationChunk();

  @override
  List<Object?> get props => [];
}

/// A text token or text delta generated by the assistant.
final class ChatTextChunk extends ChatGenerationChunk {
  const ChatTextChunk(this.text);

  final String text;

  @override
  List<Object?> get props => [text];
}

/// A reasoning/thinking delta generated by a model that exposes it separately.
final class ChatThinkingChunk extends ChatGenerationChunk {
  const ChatThinkingChunk(this.content);

  final String content;

  @override
  List<Object?> get props => [content];
}

/// A model-requested tool call.
final class ChatFunctionCallChunk extends ChatGenerationChunk {
  const ChatFunctionCallChunk({
    required this.name,
    required this.args,
  });

  final String name;
  final Map<String, dynamic> args;

  @override
  List<Object?> get props => [name, args];
}
