import 'package:equatable/equatable.dart';

/// Where chat inference should run.
enum ChatInferenceMode {
  /// Use an on-device model through lib_llama_cpp.
  local,

  /// Use a remote LLM API.
  remote,
}

/// Supported remote LLM API families.
enum RemoteLlmProvider {
  /// APIs that expose an OpenAI-compatible `/chat/completions` endpoint.
  openAiCompatible,

  /// OpenAI hosted API.
  openAi,

  /// Anthropic hosted or compatible API.
  anthropic,

  /// OpenRouter OpenAI-compatible API.
  openRouter,

  /// Groq OpenAI-compatible API.
  groq,

  /// DeepSeek OpenAI-compatible API.
  deepSeek,
}

/// Remote LLM wire protocol.
enum RemoteLlmApiType {
  /// OpenAI-compatible `POST /chat/completions`.
  openAiChatCompletions,

  /// OpenAI `POST /responses`.
  openAiResponses,

  /// Anthropic-compatible `POST /messages`.
  anthropicMessages,
}

/// Remote provider thinking/reasoning effort.
enum RemoteThinkingEffort {
  /// Disable provider-side thinking.
  off,

  /// Enable thinking with the provider's standard effort.
  high,

  /// Enable thinking with the provider's highest effort.
  max,
}

extension RemoteLlmProviderX on RemoteLlmProvider {
  String get displayName {
    return switch (this) {
      RemoteLlmProvider.openAiCompatible => 'OpenAI Compatible',
      RemoteLlmProvider.openAi => 'OpenAI',
      RemoteLlmProvider.anthropic => 'Anthropic',
      RemoteLlmProvider.openRouter => 'OpenRouter',
      RemoteLlmProvider.groq => 'Groq',
      RemoteLlmProvider.deepSeek => 'DeepSeek',
    };
  }

  String get defaultBaseUrl {
    return switch (this) {
      RemoteLlmProvider.openAiCompatible => 'https://api.openai.com/v1',
      RemoteLlmProvider.openAi => 'https://api.openai.com/v1',
      RemoteLlmProvider.anthropic => 'https://api.anthropic.com/v1',
      RemoteLlmProvider.openRouter => 'https://openrouter.ai/api/v1',
      RemoteLlmProvider.groq => 'https://api.groq.com/openai/v1',
      RemoteLlmProvider.deepSeek => 'https://api.deepseek.com/v1',
    };
  }

  RemoteLlmApiType get defaultApiType {
    return switch (this) {
      RemoteLlmProvider.openAi => RemoteLlmApiType.openAiResponses,
      RemoteLlmProvider.anthropic => RemoteLlmApiType.anthropicMessages,
      RemoteLlmProvider.openAiCompatible ||
      RemoteLlmProvider.openRouter ||
      RemoteLlmProvider.groq ||
      RemoteLlmProvider.deepSeek => RemoteLlmApiType.openAiChatCompletions,
    };
  }
}

extension RemoteLlmApiTypeX on RemoteLlmApiType {
  String get displayName {
    return switch (this) {
      RemoteLlmApiType.openAiChatCompletions => 'OpenAI Chat Completions',
      RemoteLlmApiType.openAiResponses => 'OpenAI Responses',
      RemoteLlmApiType.anthropicMessages => 'Anthropic Messages',
    };
  }
}

extension RemoteThinkingEffortX on RemoteThinkingEffort {
  String get displayName {
    return switch (this) {
      RemoteThinkingEffort.off => 'Off',
      RemoteThinkingEffort.high => 'High',
      RemoteThinkingEffort.max => 'Max',
    };
  }

  String? get deepSeekReasoningEffort {
    return switch (this) {
      RemoteThinkingEffort.off => null,
      RemoteThinkingEffort.high => 'high',
      RemoteThinkingEffort.max => 'max',
    };
  }
}

/// App-owned generation stream event.
///
/// Repositories adapt provider-specific streaming formats into this type so the
/// BLoC does not depend on a specific model SDK or HTTP API.
sealed class ChatGenerationChunk extends Equatable {
  const ChatGenerationChunk();

  @override
  List<Object?> get props => [];
}

/// A text token or text delta generated by the assistant.
final class ChatTextChunk extends ChatGenerationChunk {
  const ChatTextChunk(this.text);

  final String text;

  @override
  List<Object?> get props => [text];
}

/// A reasoning/thinking delta generated by a model that exposes it separately.
final class ChatThinkingChunk extends ChatGenerationChunk {
  const ChatThinkingChunk(this.content);

  final String content;

  @override
  List<Object?> get props => [content];
}

/// A model-requested tool call.
final class ChatFunctionCallChunk extends ChatGenerationChunk {
  const ChatFunctionCallChunk({required this.name, required this.args});

  final String name;
  final Map<String, dynamic> args;

  @override
  List<Object?> get props => [name, args];
}
