import 'dart:convert';
import 'dart:typed_data';

import 'package:equatable/equatable.dart';

/// Represents a chat message in a conversation.
sealed class Message extends Equatable {
  const Message({
    required this.id,
    required this.content,
    required this.conversationId,
    required this.timestamp,
  });

  /// Unique identifier for the message.
  final String id;

  /// The text content of the message.
  final String content;

  /// The ID of the conversation this message belongs to.
  final String conversationId;

  /// When the message was created.
  final DateTime timestamp;

  @override
  List<Object?> get props => [id, content, conversationId, timestamp];

  /// Returns the role of the message sender.
  String get role;
}

/// A file attached to a user chat message.
final class ChatAttachment extends Equatable {
  const ChatAttachment({
    required this.id,
    required this.name,
    this.sizeBytes,
    this.mimeType,
    this.bytes,
  });

  final String id;
  final String name;
  final int? sizeBytes;
  final String? mimeType;
  final Uint8List? bytes;

  String get extension => _extensionFor(name, mimeType);

  bool get isImage =>
      (mimeType?.startsWith('image/') ?? false) || _isImageExtension(extension);

  bool get isAudio =>
      (mimeType?.startsWith('audio/') ?? false) || _isAudioExtension(extension);

  bool get isText =>
      (mimeType?.startsWith('text/') ?? false) ||
      mimeType == 'application/json' ||
      _isTextExtension(extension);

  @override
  List<Object?> get props => [id, name, sizeBytes, mimeType, bytes];

  ChatAttachment copyWith({
    String? id,
    String? name,
    int? sizeBytes,
    String? mimeType,
    Uint8List? bytes,
  }) {
    return ChatAttachment(
      id: id ?? this.id,
      name: name ?? this.name,
      sizeBytes: sizeBytes ?? this.sizeBytes,
      mimeType: mimeType ?? this.mimeType,
      bytes: bytes ?? this.bytes,
    );
  }
}

/// A message sent by the user.
final class UserMessage extends Message {
  const UserMessage({
    required super.id,
    required super.content,
    required super.conversationId,
    required super.timestamp,
    this.imageBytes,
    this.audioBytes,
    this.attachments = const [],
  });

  /// Optional image data attached to this message.
  final Uint8List? imageBytes;

  /// Optional audio data attached to this message.
  final Uint8List? audioBytes;

  /// Files attached to this message.
  final List<ChatAttachment> attachments;

  /// Whether this message has an image attachment.
  bool get hasImage => imageBytes != null;

  /// Whether this message has an audio attachment.
  bool get hasAudio => audioBytes != null;

  /// Whether this message has any file attachments.
  bool get hasAttachments => attachments.isNotEmpty || hasImage || hasAudio;

  /// Text sent to models, with readable file attachments appended.
  String contentWithAttachments({int maxInlineFileBytes = 64 * 1024}) {
    final parts = <String>[
      if (content.trim().isNotEmpty) content.trim(),
      for (final attachment in attachments)
        _attachmentReferenceText(attachment, maxInlineFileBytes),
    ];
    return parts.join('\n\n');
  }

  @override
  String get role => 'user';

  @override
  List<Object?> get props => [
    ...super.props,
    imageBytes,
    audioBytes,
    attachments,
  ];

  UserMessage copyWith({
    String? id,
    String? content,
    String? conversationId,
    DateTime? timestamp,
    Uint8List? imageBytes,
    Uint8List? audioBytes,
    List<ChatAttachment>? attachments,
  }) {
    return UserMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      conversationId: conversationId ?? this.conversationId,
      timestamp: timestamp ?? this.timestamp,
      imageBytes: imageBytes ?? this.imageBytes,
      audioBytes: audioBytes ?? this.audioBytes,
      attachments: attachments ?? this.attachments,
    );
  }
}

/// A message generated by the assistant (LLM).
final class AssistantMessage extends Message {
  const AssistantMessage({
    required super.id,
    required super.content,
    required super.conversationId,
    required super.timestamp,
    this.isStreaming = false,
    this.tokenCount,
    this.thinkingContent,
    this.responseInfo,
  });

  /// Whether the message is currently being streamed.
  final bool isStreaming;

  /// The number of tokens in this message (null if not yet computed).
  final int? tokenCount;

  /// Chain-of-thought reasoning content from the model's thinking process.
  final String? thinkingContent;

  /// Generation metrics for this response, when available.
  final ChatResponseInfo? responseInfo;

  /// Whether this message has thinking/reasoning content.
  bool get hasThinking =>
      thinkingContent != null && thinkingContent!.isNotEmpty;

  @override
  String get role => 'assistant';

  @override
  List<Object?> get props => [
    ...super.props,
    isStreaming,
    tokenCount,
    thinkingContent,
    responseInfo,
  ];

  AssistantMessage copyWith({
    String? id,
    String? content,
    String? conversationId,
    DateTime? timestamp,
    bool? isStreaming,
    int? tokenCount,
    String? thinkingContent,
    ChatResponseInfo? responseInfo,
  }) {
    return AssistantMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      conversationId: conversationId ?? this.conversationId,
      timestamp: timestamp ?? this.timestamp,
      isStreaming: isStreaming ?? this.isStreaming,
      tokenCount: tokenCount ?? this.tokenCount,
      thinkingContent: thinkingContent ?? this.thinkingContent,
      responseInfo: responseInfo ?? this.responseInfo,
    );
  }
}

/// Runtime metrics captured for an assistant response.
final class ChatResponseInfo extends Equatable {
  const ChatResponseInfo({
    required this.outputTokens,
    required this.duration,
    this.contextTokens,
    this.maxOutputTokens,
  });

  /// Generated output token count. This is estimated when provider usage data
  /// is not available.
  final int outputTokens;

  /// Approximate input context size in tokens.
  final int? contextTokens;

  /// Configured maximum output tokens for the request.
  final int? maxOutputTokens;

  /// Wall-clock generation duration.
  final Duration duration;

  /// Output throughput in tokens per second.
  double get tokensPerSecond {
    final millis = duration.inMilliseconds;
    if (millis <= 0) return 0;
    return outputTokens / (millis / 1000);
  }

  @override
  List<Object?> get props => [
    outputTokens,
    contextTokens,
    maxOutputTokens,
    duration,
  ];
}

String _attachmentReferenceText(
  ChatAttachment attachment,
  int maxInlineFileBytes,
) {
  final buffer = StringBuffer()..writeln('Attached file: ${attachment.name}');
  final mimeType = attachment.mimeType;
  if (mimeType != null && mimeType.isNotEmpty) {
    buffer.writeln('Type: $mimeType');
  }
  final size = attachment.sizeBytes ?? attachment.bytes?.length;
  if (size != null) {
    buffer.writeln('Size: ${_formatBytes(size)}');
  }

  final bytes = attachment.bytes;
  if (bytes == null) {
    buffer.writeln('Content: [not available]');
  } else if (attachment.isText && bytes.length <= maxInlineFileBytes) {
    buffer
      ..writeln()
      ..writeln('```')
      ..writeln(utf8.decode(bytes, allowMalformed: true).trim())
      ..writeln('```');
  } else if (attachment.isText) {
    buffer.writeln('Content: [text file too large to inline]');
  } else if (!attachment.isText) {
    buffer.writeln('Content: [binary file omitted]');
  }

  return buffer.toString().trim();
}

String _extensionFor(String name, String? mimeType) {
  final dot = name.lastIndexOf('.');
  if (dot != -1 && dot < name.length - 1) {
    return name.substring(dot + 1).toLowerCase();
  }
  return switch (mimeType) {
    'image/png' => 'png',
    'image/jpeg' => 'jpg',
    'image/gif' => 'gif',
    'image/webp' => 'webp',
    'audio/wav' => 'wav',
    'audio/mpeg' => 'mp3',
    'audio/mp4' => 'm4a',
    'text/plain' => 'txt',
    'application/json' => 'json',
    _ => '',
  };
}

bool _isImageExtension(String extension) {
  return const {
    'jpg',
    'jpeg',
    'png',
    'gif',
    'webp',
    'bmp',
    'heic',
    'heif',
  }.contains(extension);
}

bool _isAudioExtension(String extension) {
  return const {
    'aac',
    'aiff',
    'flac',
    'm4a',
    'mp3',
    'ogg',
    'opus',
    'wav',
    'webm',
  }.contains(extension);
}

bool _isTextExtension(String extension) {
  return const {
    'csv',
    'dart',
    'diff',
    'go',
    'html',
    'json',
    'log',
    'md',
    'py',
    'rs',
    'sql',
    'swift',
    'toml',
    'ts',
    'tsx',
    'txt',
    'yaml',
    'yml',
  }.contains(extension);
}

String _formatBytes(int bytes) {
  if (bytes < 1024) return '$bytes B';
  final kb = bytes / 1024;
  if (kb < 1024) return '${kb.toStringAsFixed(0)} KB';
  return '${(kb / 1024).toStringAsFixed(1)} MB';
}

/// A system message that sets context for the conversation.
final class SystemMessage extends Message {
  const SystemMessage({
    required super.id,
    required super.content,
    required super.conversationId,
    required super.timestamp,
  });

  @override
  String get role => 'system';

  SystemMessage copyWith({
    String? id,
    String? content,
    String? conversationId,
    DateTime? timestamp,
  }) {
    return SystemMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      conversationId: conversationId ?? this.conversationId,
      timestamp: timestamp ?? this.timestamp,
    );
  }
}

/// A tool execution result fed back to the model.
final class ToolResponseMessage extends Message {
  const ToolResponseMessage({
    required super.id,
    required super.content,
    required super.conversationId,
    required super.timestamp,
    required this.toolName,
  });

  /// The name of the tool that produced this response.
  final String toolName;

  @override
  String get role => 'tool_response';

  @override
  List<Object?> get props => [...super.props, toolName];

  ToolResponseMessage copyWith({
    String? id,
    String? content,
    String? conversationId,
    DateTime? timestamp,
    String? toolName,
  }) {
    return ToolResponseMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      conversationId: conversationId ?? this.conversationId,
      timestamp: timestamp ?? this.timestamp,
      toolName: toolName ?? this.toolName,
    );
  }
}
