import 'dart:typed_data';

import 'package:equatable/equatable.dart';

/// Represents a chat message in a conversation.
sealed class Message extends Equatable {
  const Message({
    required this.id,
    required this.content,
    required this.conversationId,
    required this.timestamp,
  });

  /// Unique identifier for the message.
  final String id;

  /// The text content of the message.
  final String content;

  /// The ID of the conversation this message belongs to.
  final String conversationId;

  /// When the message was created.
  final DateTime timestamp;

  @override
  List<Object?> get props => [id, content, conversationId, timestamp];

  /// Returns the role of the message sender.
  String get role;
}

/// A message sent by the user.
final class UserMessage extends Message {
  const UserMessage({
    required super.id,
    required super.content,
    required super.conversationId,
    required super.timestamp,
    this.imageBytes,
  });

  /// Optional image data attached to this message.
  final Uint8List? imageBytes;

  /// Whether this message has an image attachment.
  bool get hasImage => imageBytes != null;

  @override
  String get role => 'user';

  @override
  List<Object?> get props => [...super.props, imageBytes];

  UserMessage copyWith({
    String? id,
    String? content,
    String? conversationId,
    DateTime? timestamp,
    Uint8List? imageBytes,
  }) {
    return UserMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      conversationId: conversationId ?? this.conversationId,
      timestamp: timestamp ?? this.timestamp,
      imageBytes: imageBytes ?? this.imageBytes,
    );
  }
}

/// A message generated by the assistant (LLM).
final class AssistantMessage extends Message {
  const AssistantMessage({
    required super.id,
    required super.content,
    required super.conversationId,
    required super.timestamp,
    this.isStreaming = false,
    this.tokenCount,
  });

  /// Whether the message is currently being streamed.
  final bool isStreaming;

  /// The number of tokens in this message (null if not yet computed).
  final int? tokenCount;

  @override
  String get role => 'assistant';

  @override
  List<Object?> get props => [...super.props, isStreaming, tokenCount];

  AssistantMessage copyWith({
    String? id,
    String? content,
    String? conversationId,
    DateTime? timestamp,
    bool? isStreaming,
    int? tokenCount,
  }) {
    return AssistantMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      conversationId: conversationId ?? this.conversationId,
      timestamp: timestamp ?? this.timestamp,
      isStreaming: isStreaming ?? this.isStreaming,
      tokenCount: tokenCount ?? this.tokenCount,
    );
  }
}

/// A system message that sets context for the conversation.
final class SystemMessage extends Message {
  const SystemMessage({
    required super.id,
    required super.content,
    required super.conversationId,
    required super.timestamp,
  });

  @override
  String get role => 'system';

  SystemMessage copyWith({
    String? id,
    String? content,
    String? conversationId,
    DateTime? timestamp,
  }) {
    return SystemMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      conversationId: conversationId ?? this.conversationId,
      timestamp: timestamp ?? this.timestamp,
    );
  }
}

/// A tool execution result fed back to the model.
final class ToolResponseMessage extends Message {
  const ToolResponseMessage({
    required super.id,
    required super.content,
    required super.conversationId,
    required super.timestamp,
    required this.toolName,
  });

  /// The name of the tool that produced this response.
  final String toolName;

  @override
  String get role => 'tool_response';

  @override
  List<Object?> get props => [...super.props, toolName];

  ToolResponseMessage copyWith({
    String? id,
    String? content,
    String? conversationId,
    DateTime? timestamp,
    String? toolName,
  }) {
    return ToolResponseMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      conversationId: conversationId ?? this.conversationId,
      timestamp: timestamp ?? this.timestamp,
      toolName: toolName ?? this.toolName,
    );
  }
}
